# Generated by Django 3.2.4 on 2021-06-24 20:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('type', models.CharField(choices=[('History', 'History'), ('Computer Science', 'Computer Science'), ('Psychology', 'Psychology'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Biography', 'Biography'), ('Finances', 'Finances'), ('Business', 'Business'), ('Negotiation', 'Negotiation'), ('Fiction', 'Fiction'), ('Autobiography', 'Autobiography'), ('Poetry', 'Poetry'), ('Meditations', 'Meditations'), ('Science', 'Science')], default=0, max_length=25)),
                ('wanting_level', models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=2)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BooksManager.author')),
            ],
        ),
        migrations.CreateModel(
            name='ToReadBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('History', 'History'), ('Computer Science', 'Computer Science'), ('Psychology', 'Psychology'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Biography', 'Biography'), ('Finances', 'Finances'), ('Business', 'Business'), ('Negotiation', 'Negotiation'), ('Fiction', 'Fiction'), ('Autobiography', 'Autobiography'), ('Poetry', 'Poetry'), ('Meditations', 'Meditations'), ('Science', 'Science')], default=0, max_length=25)),
                ('currently_reading', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BooksManager.author')),
            ],
        ),
        migrations.CreateModel(
            name='DoneToReadBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('History', 'History'), ('Computer Science', 'Computer Science'), ('Psychology', 'Psychology'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Biography', 'Biography'), ('Finances', 'Finances'), ('Business', 'Business'), ('Negotiation', 'Negotiation'), ('Fiction', 'Fiction'), ('Autobiography', 'Autobiography'), ('Poetry', 'Poetry'), ('Meditations', 'Meditations'), ('Science', 'Science')], default=0, max_length=25)),
                ('mark', models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=2)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BooksManager.author')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentReadingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('type', models.CharField(choices=[('History', 'History'), ('Computer Science', 'Computer Science'), ('Psychology', 'Psychology'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Biography', 'Biography'), ('Finances', 'Finances'), ('Business', 'Business'), ('Negotiation', 'Negotiation'), ('Fiction', 'Fiction'), ('Autobiography', 'Autobiography'), ('Poetry', 'Poetry'), ('Meditations', 'Meditations'), ('Science', 'Science')], default=0, max_length=25)),
                ('done', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BooksManager.author')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('History', 'History'), ('Computer Science', 'Computer Science'), ('Psychology', 'Psychology'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Biography', 'Biography'), ('Finances', 'Finances'), ('Business', 'Business'), ('Negotiation', 'Negotiation'), ('Fiction', 'Fiction'), ('Autobiography', 'Autobiography'), ('Poetry', 'Poetry'), ('Meditations', 'Meditations'), ('Science', 'Science')], default=0, max_length=25)),
                ('owned', models.BooleanField(default=True)),
                ('cover', models.ImageField(default='/books/default.jpg', upload_to='books/')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='BooksManager.author')),
            ],
        ),
    ]
