# Generated by Django 3.2.4 on 2021-06-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BooksManager', '0004_auto_20210625_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BooksManager.booktype'),
        ),
        migrations.AlterField(
            model_name='booktype',
            name='interesting_level',
            field=models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='currentreadingbook',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BooksManager.booktype'),
        ),
        migrations.AlterField(
            model_name='donetoreadbook',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BooksManager.booktype'),
        ),
        migrations.AlterField(
            model_name='toreadbook',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BooksManager.booktype'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BooksManager.booktype'),
        ),
    ]
