# Generated by Django 3.2.4 on 2021-06-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksManager', '0005_auto_20210625_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='donetoreadbook',
            name='cover',
            field=models.ImageField(default='/books/default.jpg', upload_to='books/'),
        ),
        migrations.AddField(
            model_name='toreadbook',
            name='cover',
            field=models.ImageField(default='/books/default.jpg', upload_to='books/'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='cover',
            field=models.ImageField(default='/books/default.jpg', upload_to='books/'),
        ),
    ]
