# Generated by Django 3.2.4 on 2021-06-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksManager', '0006_auto_20210625_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentreadingbook',
            name='cover',
            field=models.ImageField(default='/books/default.jpg', upload_to='books/'),
        ),
    ]
