# Generated by Django 3.2.4 on 2021-06-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksManager', '0007_currentreadingbook_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(default='/authors-image/default.jpg', upload_to='authors-image/'),
        ),
    ]
